services:
- docker
script:
- docker build -t xgovslackbot .
deploy:
  provider: cloudfoundry
  username: xgovslack-ci@googlegroups.com
  api: https://api.cloud.service.gov.uk
  organization: cross-government-slack
  space: sandbox
  password:
    secure: Nl2nkMlbvYQinEi2lwc5fb8k2MTjEhetpRi5ztT8/QX//c+MFnRtTQPcvvSI3x5dV47La/utFsC+KFBIosnJC2LTJ1xwgHmZ/ZM+fiUJjnt9hkCpOUMZc0p1+Nl0dSyUyv3ee/hw8iuW78tqyQw3JIxQOxFGmGX6ykQpQm01zbtYepj16nX9HvQXO6t9Hs9OzOVX/zCpApZfogZDxHJRjLHl3TiJBliGa1knhdUu4WbGkLuUVmp+9eYMtvVSoh0Qg4EoCFfjAuVDKVBDfVyDIILifHYxQACeQIy1CGHWrhgT5kRI4ocmOQSr/s0SckJ4nN4VJWjQPbKGOX3ETauICIt3lB89EMpgmvoS7fqRMHfMNnX3jYq5jRtrOp5OInFMBYwz/SXl1w/z1IH/+96AF9sl/RHZMvTTW+5R5C/5pHwNhxp+a0m+q1qK4QSBPZItgUv09WHdAYFZY9mp5r2G9SWfj3jqkhUx8BisMERqD8yWTpFWMB8ALYmIhJ4136LGifxfW1bPumin11ZwI2ZyaVV4gQINl3XwWEmIqN2LsW2ietY7jFKs8BaOWg/vtV+QRM7yi7e/QknBEIm+Mgjkop7QWRmPiKcLlL3131sd/YGG7Om/Bu69UiHskeFbXM0mgFW2CXFlymhv5geXlLAF3v52tDRi5syReJBiHrseeBQ=
  on:
    branch: master
