services:
- docker
script:
- docker build -t xgovslackbot .
deploy:
  provider: cloudfoundry
  username: xgovslack-ci@googlegroups.com
  api: https://api.cloud.service.gov.uk
  organization: cross-government-slack
  space: sandbox
  password:
    secure: ihcZUPSLQtwd1WSaQuZe8gRLpQQPTIlHzqOdrmCkt1RHYwDL6wmzyJP7dfdUtr7qix0T0UktTHMyUYA1ZFqLFdcgZmoxSQDU5uL+cQH4l64CsktP+zo9acw2ufV0BF9Ot7wh9CHFqHMKEaphdpuq/QHNZ5SHr1noNUyf52FXRDhGF5zuiqoNMC8kvUqE3BbmEKW75qX0+BFgmTFHMGbXynnDzX5YX057NldxEQR0IaqjpEQJ4TvJQ2MRHI94JcQo23gFrvp4kHILiK8MuPXyArw85hNrP59dmIhPxeKWewdRaLJKkS3rRaxIWNKvrcL0ET8ez91er5Xi4KD20pWyV5pohrpUBGjTvJZcRJRQPZFdx5lM10VvH8bm4fcXalIrKaUbtJE2qUUxjpY4DeG68pHNw1cqZ8Q+HtCTXwUVH/n9vC4pTOqbEaFsgfdtl0sym54i1+yCQxMCVjlGfDnTo9K59OdAqZrDFkUVlyV9GONX4RqRlTKw200z3AODhzXUMf2RBR2ySsI2Xk6KiRihoru4vxbxFxc+wLzsowWD/ofKNQ/ywA9SQsPN5w3CuO5G1UlfTCAGFdc+RzymZXIlZM+hDr1pf+bA9phtCNbV2gMp1JhJFtdF5A1ZYpeReTsB0CLady/GU0fb7W+2D7QaAsPua5YfGhFdIku+cdvEO50=
  on:
    branch: master
