services:
- docker
script:
- docker build -t xgovslackbot .
deploy:
  provider: cloudfoundry
  username: xgovslack-ci@googlegroups.com
  api: https://api.cloud.service.gov.uk
  organization: cross-government-slack
  space: sandbox
  password:
    secure: pMvSHm0mJtHqZonBlL6v6R4VflHZC1+N4AaDtWq0N2JVxR6atLISU2aScyNGriBt7iFOpBNp6LCydOIBDXVLlUQ3qTncNLWFJjlyalm3vzQRNQ16O3Q5L7CwPzl4eFGRdBePFgKkIAunJtZPUBtHPl8KcbUOjrSf1sbRuvwMQhgYZRpB1ZkH9XhhnAIVH7wY4Vy8367T4NRNQLZdor0Zg2PtsHjZ3sH/gEjgf2QQgV9cvlDGzhPNn3naZF0HnmXQKpxWkEAdzPaknbLEPniT5by+59WwWuoBxyxyD28OyCzvUPQRqNJgNuob5dzmvJarOtC5udupvsvqqcrq/Bp68UCDBpIaW/0e9dwUY9YoXTxnS5rfCzOgZmg4/ur9HJQzsjTG0RaSOpVodkHgthvopAYVz5xGrE3Zv3uOS2Qw89Fc/+Pk/fARZmtYFmhQqX3dXW30dSBfHlzaico7xCzpC+/JPJbb1O11MCxXJxRUDZEF3CrOMmOZlKHi57o0AlFzXJi+zh5HCw8QmXCHUUubgwq6d4TgvLgld0g/4SA8sB5ueZVqRMOUc31+wyXFUybBjnfv3TgzqyZ1EN1xcrlZ0P4PY5MPbrBWsb4cGWbEIjMKJ+TVvTXoBtN68Hu88vee+K0uF9mYwVD/7rQIA5hU+S3JC5ZiJzEwAlZJDB2yp1E=
  on:
    branch: master
