services:
- docker
script:
- docker build -t xgovslackbot .
deploy:
  provider: cloudfoundry
  username: xgovslack-ci@googlegroups.com
  api: https://api.cloud.service.gov.uk
  organization: cross-government-slack
  space: sandbox
  password:
    secure: "pF1wTcwBe/qRUC7cg2eVC0TDL7mi8dkjXnO9THlnoAtSOMGhY1kkwMbKeB6I2NzONu1hAFbT2TsDlB6ok5Iat9bC4bez0UOHaEpGhJEqubE9QB2rSGebQrJUUWU3IthOeMbLjRahFz021do0zVecIUYt3GtSWc31wovSVhOPf9O5AzIh+qTQneAxVFF6V52sn0uERUolXqGoezXVFPo56MA+/nRReE1Nb+5E819DwTcYP1BRB4N4Aal05hjN8OxfOQXew632XV3jYr0K8E70h6fZ2XcXvQP2FUusDF+XqD4prfWfHXM+H2G8A6RaEyl/XVo5lPT7kxDonCRCNZfP7D1qk2wJns1HpWAkZBmqalr8AG7CjEDfHPl4O7mJ7Lthp67/SX7q8eDetxWudDvw+SNklreYY8ad0W3Eng76bqspJTElVModDNMOIduDluNdx66/6h+0HKF9eUMjtwV4umJnSoSyX4+x5TfJ/HwjwNLGMNTmJkGqIaz2x7T58iNkKSgCCR5LVWQcELNN5y31Sb0HOUy17Whlb4+S1mAzSZJslPpR2DAT2Uc8akF2U2aVnX6V2P/TX5lNMkKc+ZfbLhUYSkbVtiJyANOOA5cxF8D17aJDH6N1naVvk+cvtTtK/AHctrIJAa+/WCYCxOC96S/PLZVzm0inluRAsBicLSo="
  on:
    branch: master
