services:
- docker
script:
- docker build -t xgovslackbot .
deploy:
  provider: cloudfoundry
  username: michael.bruntonspall@digital.cabinet-office.gov.uk
  api: https://api.cloud.service.gov.uk
  organization: cross-government-slack
  space: sandbox
  password:
    secure: NU0SKikkfRp5MQW6fzU6fdaNTA/g5p42ly9tSfIiyHPdBmYKeJ+dPcuPj+vJTSKw6xKACYj5dx3q6pn0qAaunGV16zxUJjiuywCPFs8Fc0ZTSD5i7XR9rReW2z20Gt6lOkf1664JpioN5fPeKK8mu35MXrGFqfvcbQvRajJ5Fu/hM/Sv1QtEpf8FbAhEi3gpeXt7n3IrHaJo5Z9M2alACAU2grgdWFODIMKeLOXAiGGTX02jmeyD54Hwn000Xxo4afI3BeExtXJ0yKjJpCZ9eSQJ1a3gv+94ZE7u0M/PG7GhzpdSvjS7GWiJfAJ321B4gAVhb+2X58Wr1C23AB86p+KFTS7B3ehrPxgNHb4IQoafAieWIAsGvb7tfG3garVfc3i/ArKtYRGd43/1Cqj/bnO95xbJHRxlnRLuhxTk/0bvfXKeArup8x3AKYWnu7JnFI4PIoJp8MNVKtLQ3Tqkw0o/xuQ7eS/jzQ4g76nRtof5WqeKW4C7aZISkPUMaVeCqXugr9qwKerru7aSOd+JNejl0doH0tSi4aLgcRcjjcyE3hgSCebbWKXSDPrGfaUpwm1aRyrWBfoJ9pPmgFoyn4qLwYXY0R9nL5Sj9oX6c+rh8CCXOcRs/Ac1lNV/TIToArTahPDxJud6fkWP0F1fX0YouLVKZDiCntBfA0l7c7w=
  on:
    branch: master
