services:
- docker
script:
- docker build -t xgovslackbot .
deploy:
  provider: cloudfoundry
  username: xgovslack-ci@googlegroups.com
  api: https://api.cloud.service.gov.uk
  organization: cross-government-slack
  space: sandbox
  password:
    secure: pYWEXzwLLwDD1/8tRdBgJ7cbOFiVY9JF57QrNe3kPmWSh7vpWNljzWpOpFESZ/pxjP727jiDj8/U39Ty/rSe9azgmPYQr9nCK3u+MSUcLZYdEY40e2qz6GxS4QaXVoGK8/v4zKiH1FK4SyAp+yAtuqL0artT31G0A/dJtFkrwO8aUkEAslPpxWnJMHoEEk17qi6tL/57iyd0Q1Tt3Yq28cC1xAA0cpQFdiBxcWt6nlRgYARNLWcgaS70Svb5KfRwi0CNYn2bNkQz8cScgcSyP6efy3QOFqoVi0LMaDVmoTTpt+DLw7EDTXPmCIvJr48vap00SWIqgqcioEV3SyZLEUJkHU203A6h2L96u7kuYa9SGRqpAV/xxO6f1z68I2gbdRxgW3RZ6BJvdu0iq0xAgf2w0G1seUBy5dSMrAGW34dNUH0ksTZ38QKDKv3BtqcpVZNiG9+U5cjym640UGfDiQo0ixfsTJHvg/KosvIGKUZdGJUOuXXY4ZPa3pC4RzMAVH0K71Z3qYem69XHMktXgysqCuAGNwEBDQ6nFbdpOTBkMttGi1UTw97oFr9cN444f4JpipPq3LUkPAtzZp0bMw1pVruL3qsLkuDWvM0kZORiU9wrxHt27oXwjFElm73dbRkGtOWYhJ7WxCXpmSrB/l3UhfoylLslFX66ChX0C2A=
  on:
    branch: master
