services:
- docker
script:
- docker build -t xgovslackbot .
deploy:
  provider: cloudfoundry
  username: xgovslack-ci@googlegroups.com
  api: https://api.cloud.service.gov.uk
  organization: cross-government-slack
  space: sandbox
  password:
    secure:  "KR+0IGOIg7Sf18XNSoYrw/AdbLv30afhrZktiz8DrQV/w7IyejBocdswekN9QmzNk8U78IFckCZ8+o28QCszhwWVthzajhASwYSUYZzvVyiIv0UHkpbHtMMCvZR3sIzNQe0PO/lhvQ/kAhXXWUHBrDLeFXTYGFsadFhoOl+/sfUqVs+anFZF0cAxCxbQALOH+ZiTY4ftQ0uyRFjOiiaTsI8chsdX4kHDkUZz6e4dZaXyD7BJHRJz1e6xd2hhjTte2Mrz4Ng6L8g88+BO5rRtf/GlTsZo1keme/3lEgLgrfpdOmQ98lRHT9nWCwPBB254Cs1t60N2FjXJN+t1k1+9bbynSLqcEIC60FXmSw8GynwvcMxiPqJYGaVHrlGAlCZGWh3HrKEnFRQypAIJgtRy7PVQzDEbyK3wtc9LwpRd38bp3P5WPa7uDqIZas5ymxtIsxIH2Ow4RbmCva2aSfyVIeDW7wDHPRPWKIpkPpFBgezT5fLCKzRPwmsl2FU7BOO3XgqXFXqgR84t1ykl3qpHaXmQgkw8DMz1Qwym/Ol198jqqfMb4hhmEPOhmv46HRg9r9iZ/YZaNSV9EnRopaMxlbephs9tFAyk13tA/uc5pVTH9WRe7wojRwKage/YK+RLoYxa1vJi0JptSkbiAUscpGOXBv0UPkAFcd0dPj4/g2c="
  on:
    branch: master
