services:
- docker
script:
- docker build -t xgovslackbot .
deploy:
  provider: cloudfoundry
  username: xgovslack-ci@googlegroups.com
  api: https://api.cloud.service.gov.uk
  organization: cross-government-slack
  space: sandbox
  password:
    secure: "Qdz4WtPl9yxjjBZ7WUzv9RCdzvQCVo0vNJcmkOsOhxie/YxFJQV475HvAWFEBYUkudLVDZSyS5AmkE3S5/q6r4QoSxZ0/Vg5muhsYe6zFklZiBPstHWx88a968DLhWdThGTGi9LI1TsffBfhxqxC+QNMdaPPGfTNvJkJuygz9EXkCqgF0Gzz/EHEVEYe0xIVpJ19mvpcJCgBUppRGble4CzUZqjFtYixkI8+qwxCNqrGXskAnRX/fPBMyhEC5Ix9G8avOPARe0wjcb7bfg9TcBuy0qbJhnn4/h6ffkFkQizHLL+YbOo3iDrU1AeR40RbIRIrJ+aasqS5HKENSq0RzlR9eSGWsdxdt6UgH8qKUeSZCXgy32midKuWFCgkooPdExzfQutlGRrrSLptGJDOgxV6534yr/KnR3GAyBGzbPhcXcYJbw97p4cUKp7XU2vmWj/Vaniup0o2m5rrd7g2pzBfVKZG2jG5dc2xLyrxgyF1DGYUKT5h9g3EDLhClZOK4qbfzkHC6cEaSmoOvWUGE0VhQAqLwfaAWYSPBTbAEkkCOPNAb8bw8pNirT+aARIbsHB8mZ5JJvlBVmlC5HLXpBCIp1LQHOftAUHRIgitN/+CvYUhb10SHRESOAarQl3K4PF2IEfJFvqEjBE4lSUNWq470ZPNIrlbuMmYpDGDv04="
  on:
    branch: master
