services:
- docker
script:
- docker build -t xgovslackbot .
deploy:
  provider: cloudfoundry
  username: michael.bruntonspall@digital.cabinet-office.gov.uk
  api: https://api.cloud.service.gov.uk
  organization: cross-government-slack
  space: sandbox
  password:
    secure: M6sygzYk9oDpbu/p34aEm+U08/LX/wiwhnZbcxk21KN6A2kEr142zISaSJqICzern/SCmJeNy04XMkWI9EsuqU5ZN18GMxRc6p75x9YkO9M1BtOWiDNDpFQV+yvaGZ01TDMS7MQ9elCWitsgHZsCCXZfD++88lNKxE6jt4ibc/WgX/I3ObhqpDTZZ/UeHDmcQz+Cf93LE4yst/UPQGJoauyrGLjxfnHec709uLualAHVsSWRTvY4AOXLTTIbvWNKDNzuQ8vfbXbHjwZT3kmjGOYelbIgn4RfuwC7OeUA3F2S8h6ZTukyAJZgI3eh3ERnsg76yZqvjNbv8LHh+vhUk7w9wVDFRXMCbBrh19HsP/sRS+hS1E2mnhKQJsyZjns4G3FdTY4GgLCG7MNP9/nau1KtbjCdCdTuttpO6cZwd2pZPQ6l8ntygZOmUdC+oa98KBFRoExwEVAdpMTZ6dRtaROSP2V2SreXTUWD32oLbXKRpAzZ0gVVVMSYyZVJqnP+NOE7+8GN2f/tAmeNdnTi5zkRfBeRjNFMARyU8mqz3HHVj00myJ55oab39LPzNSBbj8D2Q26tGnTrdMjg8nsPGz65m3c3sPnOQq2t2GT+KYYrIzZFYGiKQiMEwTyE6sGwazDSVdbZPicGNtiLLLCX1HzErvFj1bWX2yKHCpAC2+c=
  on:
    branch: master
